import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { access, copyFile } from "node:fs/promises";
import { constants as fsConstants } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "../..");
const pluginRoot = __dirname;

async function copyIfExists(src, dest) {
	try {
		await access(src, fsConstants.F_OK);
		await copyFile(src, dest);
	} catch (error) {
		if (error?.code !== "ENOENT") {
			console.error(`[copy-static] Failed to copy ${src}:`, error);
		}
	}
}

const copyStaticPlugin = {
	name: "copy-static",
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) {
				return;
			}

			await copyIfExists(
				path.join(pluginRoot, "manifest.json"),
				path.join(projectRoot, "manifest.json"),
			);
			await copyIfExists(
				path.join(pluginRoot, "styles.css"),
				path.join(projectRoot, "styles.css"),
			);
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "../../main.js",
	minify: prod,
	plugins: [copyStaticPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
